### ISSUE TITLE
Chapter 11, page 470, incorrect explanation

### ISSUE THREAD

**Issue by qingchengshang** [headfirstpython/second#1]
![request](https://github.com/user-attachments/assets/26946e60-f8fb-4c42-a95f-1c9673a4b63c)

Please refer to the following code:

`import time
from threading import Thread

from flask import Flask, render_template, request
from vsearch import search4letters

app = Flask(__name__)

app.config['dbconfig'] = {'host': '127.0.0.1',
                          'user': 'you_user_name',
                          'password': 'you_password',
                          'database': 'logDB',
                          }

@app.route('/')
@app.route('/entry')
def entry_page() -> 'html':
    """Display this webapp's HTML form."""
    return render_template('entry.html',
                           the_title='Welcome to search4letters on the web!')

@app.route('/search4', methods=['POST'])
def do_search() -> 'html':
    """Extract the posted data; perform the search; return results."""
    phrase = request.form['phrase']
    letters = request.form['letters']
    title = 'Here are your results:'
    results = str(search4letters(phrase, letters))
    try:
        t = Thread(target=log_request, args=(phrase, letters, title, results))
        t.start()
    except Exception as err:
        print('***** Logging failed with this error:', str(err))
    return render_template('results.html',
                           the_title=title,
                           the_phrase=phrase,
                           the_letters=letters,
                           the_results=results, )

def log_request(phrase, letters, title, res: str) -> None:
    """Log details of the web request and the results."""
    time.sleep(15)
    print(phrase, letters, title, res)

app.secret_key = 'YouWillNeverGuessMySecretKey'

if __name__ == '__main__':
    app.run(debug=True)
`

Root cause:
Flask's request object is context-based and can only be accessed in the thread processing the request.
When you put the log_request function into a separate thread, the new thread does not have Flask's request context and therefore cannot access the request object.

**Comment by headfirstpython** [comment]
Thanks for that clarification.
